### PR TITLE
Update newrelic-extension.js

### PR DESCRIPTION
**Pull request by benoitemile**

### CODE REVIEW

**Review by solocommand — APPROVED** [review]

**Comment by solocommand** [comment]
@localshred Any chance this can get merged and published?

**Comment by localshred** [comment]
@solocommand @benoitemile apologize for the radio silence. I killed my github notifications months ago. Merged and released this under 0.1.1.

**Comment by benoitemile** [comment]
no worries, thank you 😄

**Comment by solocommand** [comment]
Awesome, thanks!

**Comment by vladanpaunovic** [comment]
Closes #2

**Pull request merged**
